dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c
os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - valgrind
            - cppcheck
            - make
            - cmake
            - lcov


env:
    # список переменных окружения, влияющих на матрицу сборки:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=x86 BUILD_CONFIGURATION=Release


matrix:
    exclude:
        # вручную исключим ненужные элементы из матрицы сборки:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release


script:
    # скрипт сборки и тестирования проекта:
    - cd ./filemetrics
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
    - cmake --build .
        
    - cd ../..
        
    - cd ./filemetrics_multithreaded
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
    - cmake --build .
        
    - cd ../..
        
    - cd ./multi_test
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
    - cmake --build .
        
    - cd ../..
        
    - cd ./non_thread_test
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
    - cmake --build .
        
    - cd ../..
        
    - cd ./test
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DCMAKE_C_FLAGS="--coverage" -DCMAKE_CXX_FLAGS="--coverage"
    - cmake --build .
        
    - cd ../..

    - chmod u+x gtest_runer.sh
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "${CC_FOR_BUILD}" =~ gcc$ ]]; then ./gtest_runer.sh; fi
    - cd filemetrics
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=warning,performance,information src/*.c; fi
    - cd ..
    - cd filemetrics_multithreaded
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=warning,performance,information src/*.c; fi
    - cd ..
    - ./multi_test/build/multi_test main_test_dir 2
   # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./non_thread_test/build/non_thread_test main_test_dir; fi
   # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./multi_thread_test/build/multi_thread_test main_test_dir 2; fi
   # - ./test/build/test_all non_thread_test/build/non_thread_test multi_thread_test/build/multi_thread_test main_test_dir